//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourManagementEntities : DbContext
    {
        public TourManagementEntities()
            : base("name=TourManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<ExpenseType> ExpenseTypes { get; set; }
        public virtual DbSet<GITDetail> GITDetails { get; set; }
        public virtual DbSet<GroupInclusiveTour> GroupInclusiveTours { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<TourDetail> TourDetails { get; set; }
        public virtual DbSet<TourGuide> TourGuides { get; set; }
        public virtual DbSet<TourGuideWithGIT> TourGuideWithGITs { get; set; }
        public virtual DbSet<TourPrice> TourPrices { get; set; }
        public virtual DbSet<TourType> TourTypes { get; set; }
    }
}
