//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int Id { get; set; }
        public string TourId { get; set; }
        public string TourName { get; set; }
        public string TourFeature { get; set; }
        public string TourDep { get; set; }
        public string TourDes { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string TourTypeId { get; set; }
    }
}
